// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SalesTracker.Core.Data;

#nullable disable

namespace SalesTracker.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260125113930_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SalesTracker.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "PV-BAT B2C"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "PV-BAT B2B"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "WeVolt"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Lightweight PV"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "BESS"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Charge"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "ALSB"
                        });
                });

            modelBuilder.Entity("SalesTracker.Core.Entities.CategoryTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Year", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("IX_CategoryTargets_Year_CategoryId");

                    b.ToTable("CategoryTargets");
                });

            modelBuilder.Entity("SalesTracker.Core.Entities.LeadChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("LeadChannels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 25, 11, 39, 29, 843, DateTimeKind.Utc).AddTicks(9147),
                            IsActive = true,
                            Name = "Eigen leads"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 25, 11, 39, 29, 843, DateTimeKind.Utc).AddTicks(9151),
                            IsActive = true,
                            Name = "Davy"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 25, 11, 39, 29, 843, DateTimeKind.Utc).AddTicks(9153),
                            IsActive = true,
                            Name = "SMA"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 25, 11, 39, 29, 843, DateTimeKind.Utc).AddTicks(9154),
                            IsActive = true,
                            Name = "SolarWatt"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 25, 11, 39, 29, 843, DateTimeKind.Utc).AddTicks(9155),
                            IsActive = true,
                            Name = "Wienerberger"
                        });
                });

            modelBuilder.Entity("SalesTracker.Core.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CafcaHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CafcaMargin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FinalInvoiceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LeadChannelId")
                        .HasColumnType("integer");

                    b.Property<string>("LostReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("ManualMargin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("Purchase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Projects_CategoryId");

                    b.HasIndex("LeadChannelId")
                        .HasDatabaseName("IX_Projects_LeadChannelId");

                    b.HasIndex("Date", "Status")
                        .HasDatabaseName("IX_Projects_Date_Status");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("SalesTracker.Core.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("IX_SystemSettings_Key");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "HourlyRate",
                            UpdatedAt = new DateTime(2026, 1, 25, 11, 39, 29, 843, DateTimeKind.Utc).AddTicks(9175),
                            Value = "50"
                        });
                });

            modelBuilder.Entity("SalesTracker.Core.Entities.CategoryTarget", b =>
                {
                    b.HasOne("SalesTracker.Core.Entities.Category", "Category")
                        .WithMany("Targets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SalesTracker.Core.Entities.Project", b =>
                {
                    b.HasOne("SalesTracker.Core.Entities.Category", "Category")
                        .WithMany("Projects")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesTracker.Core.Entities.LeadChannel", "LeadChannel")
                        .WithMany("Projects")
                        .HasForeignKey("LeadChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("LeadChannel");
                });

            modelBuilder.Entity("SalesTracker.Core.Entities.Category", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Targets");
                });

            modelBuilder.Entity("SalesTracker.Core.Entities.LeadChannel", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
